from app.imagine.constants import Style

STYLES = {
    "anime": Style.ANIME_V2,
    "portrait": Style.PORTRAIT,
    "creative": Style.V4_CREATIVE,
    "cosmic": Style.COMIC_V2,
    "marble": Style.MARBLE,
    "disney": Style.DISNEY,
    "minecraft": Style.MINECRAFT,
    "macro": Style.MACRO_PHOTOGRAPHY,
    "gta": Style.GTA,
    "ghibli": Style.STUDIO_GHIBLI,
    "dystopian": Style.DYSTOPIAN,
    "surreal": Style.SURREALISM,
    "graffiti": Style.GRAFFITI,
    "realistic": Style.REALISTIC,
    "comic": Style.COMIC_V2,
    "rainbow": Style.RAINBOW,
    "medieval": Style.MEDIEVAL,
    "origami": Style.ORIGAMI,
    "pattern": Style.PATTERN,
    "fantasy": Style.FANTASY,
    "neon": Style.NEON,
    "haunted": Style.HAUNTED,
    "kawaii": Style.KAWAII_CHIBI,
    "samurai": Style.SAMURAI,
    "painting": Style.PAINTING,
    "icon": Style.ICON,
    "cyberpunk": Style.CYBERPUNK,
    "architecture": Style.ARCHITECTURE,
    "retro": Style.RETRO,
    "futuristic": Style.FUTURISTIC,
    "polaroid": Style.POLAROID,
    "sketch": Style.SKETCH,
    "chromatic": Style.CHROMATIC,
    "popart": Style.POP_ART
}